### ISSUE TITLE
how to create a custom function in cell ？

### ISSUE THREAD

**Issue by JiffyChen** [ONLYOFFICE/onlyoffice.github.io#86]
How to create a custom function in cell or set cell auto call macros inner function with param？

**Comment by askonev** [comment]
@JiffyChen It is not possible to run a user method in a cell because there is no such entity in the editors. You can write a script or a plugin that manipulates the data in the cell. Scenarios where you enter data into a cell and a user function automatically runs as a parameter on the data you entered cannot be implemented at the moment.

**Comment by JiffyChen** [comment]
thank you
